name: Generate iCalendar File
on:
  schedule:
    - cron: '0 * * * *'  # Jede Stunde aktualisieren
  push:
    branches:
      - main
  repository_dispatch:
    types: [new_event]  # ICS wird jetzt auch bei neuen Events aktualisiert!

jobs:
  update_ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Issues and Generate ICS
        run: |
          echo "BEGIN:VCALENDAR" > events.ics
          echo "VERSION:2.0" >> events.ics

          issues=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues?labels=Kalender" | jq -c '.[]')

          echo "$issues" | while IFS= read -r issue; do
            TITLE=$(echo $issue | jq -r '.title')
            DATE=$(echo $issue | jq -r '.title | split(" am ") | last')
            DESC=$(echo $issue | jq -r '.body')

            # Extrahiere die Teilnehmerliste, falls vorhanden
            PARTICIPANTS=$(echo "$DESC" | sed -n 's/Teilnehmer: //p')

            # Falls mehrere Teilnehmer vorhanden sind, formatieren wir sie für ICS
            ICS_ATTENDEES=""
            if [ ! -z "$PARTICIPANTS" ]; then
              IFS=', ' read -ra ADDR <<< "$PARTICIPANTS"
              for participant in "${ADDR[@]}"; do
                ICS_ATTENDEES+="ATTENDEE:$participant\n"
              done
            fi

            echo "BEGIN:VEVENT" >> events.ics
            echo "SUMMARY:$TITLE" >> events.ics
            echo "DESCRIPTION:$DESC" >> events.ics
            echo -e "$ICS_ATTENDEES" >> events.ics
            echo "DTSTART:${DATE//-/}" >> events.ics  # YYYYMMDD Format
            echo "DTEND:${DATE//-/}" >> events.ics
            echo "END:VEVENT" >> events.ics
          done

          echo "END:VCALENDAR" >> events.ics

      - name: Commit and Push ICS File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add events.ics
          git commit -m "Update .ics file"
          git push
