name: Generate iCalendar File
on:
  schedule:
    - cron: '0 * * * *'  # Aktualisiert jede Stunde
  push:
    branches:
      - main
  repository_dispatch:
    types: [new_event]

jobs:
  update_ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Issues and Generate ICS
        run: |
          echo "BEGIN:VCALENDAR" > events.ics
          echo "VERSION:2.0" >> events.ics
          echo "PRODID:-//GitHub Calendar//DE" >> events.ics
          echo "CALSCALE:GREGORIAN" >> events.ics
          echo "METHOD:PUBLISH" >> events.ics

          issues=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?labels=Kalender" | jq -c '.[]')

          echo "$issues" | while IFS= read -r issue; do
            TITLE=$(echo $issue | jq -r '.title')
            DATE=$(echo $issue | jq -r '.title | split(" am ") | last')
            DESC=$(echo $issue | jq -r '.body')

            # Teilnehmer extrahieren
            PARTICIPANTS=$(echo "$DESC" | sed -n 's/Teilnehmer: //p')

            ICS_ATTENDEES=""
            if [ ! -z "$PARTICIPANTS" ]; then
              IFS=', ' read -ra ADDR <<< "$PARTICIPANTS"
              for participant in "${ADDR[@]}"; do
                ICS_ATTENDEES+="ATTENDEE:$participant\n"
              done
            fi

            echo "BEGIN:VEVENT" >> events.ics
            echo "UID:$(uuidgen)" >> events.ics
            echo "DTSTAMP:$(date -u +"%Y%m%dT%H%M%SZ")" >> events.ics
            echo "DTSTART:${DATE//-/}" >> events.ics
            echo "DTEND:${DATE//-/}" >> events.ics
            echo "SUMMARY:$TITLE" >> events.ics
            echo "DESCRIPTION:$DESC" >> events.ics
            echo -e "$ICS_ATTENDEES" >> events.ics
            echo "END:VEVENT" >> events.ics
          done

          echo "END:VCALENDAR" >> events.ics

      - name: Commit and Push ICS File
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add events.ics
          git commit -m "Auto-update events.ics" || echo "No changes to commit"

          git pull origin main --rebase
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/OnkelHomie/calender.git
